# 自动将新开的 issue 分配给自己
name: Assign Issue to Myself

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to me
        uses: peter-evans/assign-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          assignees: 'zxc7563598'
